name = "telegram-competition-bot"
main = "main.py"
compatibility_date = "2025-01-01"
compatibility_flags = ["python_workers"]

[env.production.vars]
# Set your bot token as an environment variable

[[env.production.d1_databases]]
binding = "DB"
database_name = "challengebot-database"
database_id = "090fbfd2-4b22-49a8-ae8d-8b8b99417392"

[env.development]
[env.development.vars]
# Development environment variables

[[env.development.d1_databases]]
binding = "DB"
database_name = "challengebot-database"
database_id = "090fbfd2-4b22-49a8-ae8d-8b8b99417392"